Dz8 tooltip
js-tasks-ru/htmlcss-20220120_aasolovkina pull request #15
Opened 2022-02-04 18:13 UTC by AnnaSolovkina

2022-02-04 18:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-04 18:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-04 19:25 UTC, GSemikozov requested changes

2022-02-04 19:25 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +body {
это просто удалим

2022-02-08 21:53 UTC, GSemikozov approved these changes

2022-02-08 21:53 UTC, merged