input
js-tasks-ru/htmlcss-20220120_aasolovkina pull request #28
Opened 2022-02-22 20:41 UTC by AnnaSolovkina

2022-02-22 20:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-24 10:44 UTC, GSemikozov requested changes

2022-02-24 10:44 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input.input_success .input__input,
можно вместо .input.input_success просто .input_success

2022-02-24 10:44 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input.input_invalid .input__input {
и тут

2022-02-24 10:44 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +::placeholder {
здесь речь о конкретной внутренней реализации инпута, поэтому - .input::placeholder )

2022-02-26 11:40 UTC, GSemikozov approved these changes

2022-02-26 11:40 UTC, merged